### ISSUE TITLE
百度网盘资源失效

### ISSUE THREAD

**Issue by 2020-mmm-dev** [Yin-Hongwei/music-website#67]
静态资源获取不到，可以重新发一份连接吗

**Comment by Yin-Hongwei** [comment]
> 静态资源获取不到，可以重新发一份连接吗

可以访问啊，你再点一下

**Comment by 2020-mmm-dev** [comment]
此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！   分享链接我这边打开是这样的

**Comment by 2020-mmm-dev** [comment]
2333

**Comment by Yin-Hongwei** [comment]
链接: https://pan.baidu.com/s/1euWOlwZsIRJPiBbUS_5Qig  密码: a2r7

**Comment by 2020-mmm-dev** [comment]
好的

**Comment by shijiahao-hunan** [comment]
你好，我下载的data，song文件夹里面中文会乱码，导致听不了中文歌怎么办

**Comment by Yin-Hongwei** [comment]
> 你好，我下载的data，song文件夹里面中文会乱码，导致听不了中文歌怎么办

你换个解压工具呢，资源是没有问题的

**Comment by shijiahao-hunan** [comment]
好的可以啦，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yin-Hongwei/music-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yin-Hongwei/music-website] 百度网盘资源失效 (#67)





  
你好，我下载的data，song文件夹里面中文会乱码，导致听不了中文歌怎么办
  
你换个解压工具呢，资源是没有问题的
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
